export const publisherLinks = {
  swiftui: 'https://orangeava.com/products/ultimate-swiftui-handbook-for-ios-developers',
  firebase: 'https://orangeava.com/products/ultimate-firebase-for-ios-and-android-applications',
  course: 'https://www.udemy.com/course/swiftui-essentials-kickstart-your-ios-development-journey/',
};
export const books = [
  { title: 'Ultimate SwiftUI Handbook for iOS Developers', date: '2023-10-03', isbn: '9789388590938', url: publisherLinks.swiftui, image: require('../../Image/SwiftUI.jpg'), text: 'A practical introduction to building iOS interfaces with SwiftUI, progressing from foundational concepts to more advanced techniques.' },
  { title: 'Ultimate Firebase for iOS and Android Applications', date: '2024-10-29', isbn: '9789348107596', url: publisherLinks.firebase, image: require('../../Image/Firebase.JPG'), text: 'Firebase for mobile development on both iOS and Android, including authentication, databases, and backend integration.' },
];
const evidence = [
  { label: 'SwiftUI book — Orange AVA', href: publisherLinks.swiftui },
  { label: 'Firebase book — Orange AVA', href: publisherLinks.firebase },
  { label: 'SwiftUI Essentials — Udemy', href: publisherLinks.course },
  { label: 'LinkedIn — James Thang', href: 'https://www.linkedin.com/in/jamesthang/' },
];
const aboutSections = [
  { title: 'Apple platforms, from interface to release', paragraphs: ['My focus is native iOS development with Swift, SwiftUI, and UIKit, alongside independent macOS applications. I work on interfaces, data flows, backend integrations, platform features, purchases, and App Store preparation.', 'React Native is a supporting capability for projects with a shared mobile foundation. I also work with Codex, Claude Code, and Cursor, pairing agent-assisted implementation with code review and testing.'], links: [{ label: 'Discuss an iOS project', href: '/ios-consulting' }] },
  { title: 'Building, writing, and teaching', paragraphs: ['My portfolio includes Vola, an AI note taker for iPhone; Tidora, a Mac cleaning utility; and Horology Studio, an interactive watch experience. These independent products sit alongside my technical books and SwiftUI course.', 'I wrote Ultimate SwiftUI Handbook for iOS Developers and Ultimate Firebase for iOS and Android Applications, published by Orange AVA. My Udemy course introduces learners to SwiftUI through interface building, state, navigation, and MVVM.'], links: [{ label: 'Explore the books', href: '/books' }, { label: 'Learn SwiftUI', href: '/swiftui-training' }] },
  { title: 'One person, several published name formats', paragraphs: ['I use James Thang professionally. My Vietnamese name is Dương Đình Bảo Thăng. Publisher records use Dương Đình Bảo (James) Thăng or Duong Dinh Bao (James) Thang, and my Udemy instructor listing uses Thăng Dương. These listings refer to my work.'], links: evidence },
];
export const professionalPages = {
  '/about': { title: 'James Thang — iOS specialist, author & instructor', description: 'Meet James Thang (Dương Đình Bảo Thăng), an iOS specialist, SwiftUI instructor, and author of books on SwiftUI and Firebase.', eyebrow: 'ABOUT JAMES', heading: 'An iOS specialist who builds, writes, and teaches.', intro: 'I’m James Thang (Dương Đình Bảo Thăng), an independent iOS developer specializing in SwiftUI and UIKit, a technical author, and a SwiftUI course instructor.', translation: '/vi/about', sections: aboutSections },
  '/ios-consulting': { title: 'iOS & SwiftUI consulting | James Thang', description: 'Work with James Thang on SwiftUI and UIKit interfaces, Firebase integration, iOS product development, and App Store preparation.', eyebrow: 'FOR FOUNDERS & PRODUCT TEAMS', heading: 'Move your iOS product forward.', intro: 'I help turn product requirements into practical iPhone and iPad experiences, with hands-on work in SwiftUI, UIKit, and the details around shipping an app.', sections: [
    { title: 'Where I can help', paragraphs: ['New iOS interfaces and features, improvements to an existing app, SwiftUI and UIKit integration, Firebase-backed data flows, and App Store preparation are areas we can discuss.', 'I also develop independent macOS apps and work with React Native. The right scope depends on your product, supported platforms, existing code, and delivery constraints.'] },
    { title: 'Start with the product and the code', paragraphs: ['Share the problem you want to solve, your target users, the app’s current stage, and the platforms you support. If there is an existing codebase, tell me about its architecture and the feature or behavior that needs attention.', 'From there, we can agree on a focused scope, priorities, deliverables, and how to review the work. Timing and engagement details are discussed after understanding the project.'], links: [{ label: 'Visit my contact page', href: '/contact' }] },
    { title: 'See the product work', paragraphs: ['Vola illustrates a recording and note-taking experience on iPhone. Tidora brings scanning and cleanup tasks to macOS. Horology Studio combines watch customization with widgets and alarms. Explore these product walkthroughs to see the kinds of experiences I build.'], links: [{ label: 'Vola — AI Note Taker', href: '/case-studies/vola' }, { label: 'Tidora — Mac Cleaner', href: '/case-studies/tidora' }, { label: 'Horology Studio', href: '/case-studies/horology-studio' }] },
  ] },
  '/swiftui-training': { title: 'Learn SwiftUI with James Thang | Course & training', description: 'Explore James Thang’s SwiftUI Essentials course, learning topics, and SwiftUI book. Discuss learning needs for yourself or your team.', eyebrow: 'FOR SWIFTUI LEARNERS & TEAMS', heading: 'Learn to build interfaces you understand.', intro: 'Learn SwiftUI with an instructor who also builds independent apps and writes mobile development books. Start with my self-paced course, then discuss the topics you want help with.', translation: '/vi/swiftui-training', course: true, sections: [
    { title: 'A practical starting point', paragraphs: ['SwiftUI Essentials: Kickstart Your iOS Development Journey is my English-language course on Udemy. It introduces SwiftUI interface building, layout, state management, navigation, and MVVM through practical learning.', 'You’ll need access to a Mac with Xcode to follow along. Familiarity with basic Swift concepts will help you focus on the interface and data-flow lessons. Check the course listing for its current curriculum and enrollment details.'], links: [{ label: 'View the course and curriculum on Udemy', href: publisherLinks.course }] },
    { title: 'What to practice', items: ['Compose interfaces from views and layout containers.', 'Understand where state belongs and how changes reach the interface.', 'Build navigation between screens.', 'Organize view and model responsibilities with MVVM.'], paragraphs: ['A useful next step is to apply each topic to a small app of your own, explain the choices, and test the behavior as the data changes.'], links: [{ label: 'Read: choosing SwiftUI and UIKit', href: '/articles/swiftui-or-uikit' }] },
    { title: 'Learning needs beyond the course', paragraphs: ['If you are learning independently or planning learning for a team, send me your current experience, target topics, and what you want to build. We can discuss whether a focused session or tailored learning scope would be a good fit.', 'For a book-length companion, explore Ultimate SwiftUI Handbook for iOS Developers.'], links: [{ label: 'Discuss your learning goals', href: '/contact' }, { label: 'Explore my books', href: '/books' }] },
  ] },
  '/books': { title: 'SwiftUI & Firebase books by James Thang', description: 'Books by James Thang: Ultimate SwiftUI Handbook for iOS Developers and Ultimate Firebase for iOS and Android Applications. Publisher links, dates, and ISBNs.', eyebrow: 'TECHNICAL AUTHORSHIP', heading: 'Mobile development, explained in depth.', intro: 'Two books on building mobile applications, published by Orange AVA under my author name Dương Đình Bảo (James) Thăng.', books: true, sections: [
    { title: 'An independent educational reference', paragraphs: ['The Universidad Carlos III de Madrid syllabus for Programming Financial Mobile Applications, academic year 2025/2026, lists Ultimate Firebase for iOS and Android Applications in its basic bibliography.'], links: [{ label: 'Read the official UC3M syllabus (PDF)', href: 'https://aplicaciones.uc3m.es/cpa/cpa/generaFichaPDF?ano=2025&asignatura=17876&idioma=2&plan=461' }] },
    { title: 'Continue learning', paragraphs: ['Prefer guided video learning? My SwiftUI Essentials course covers the foundations of composing interfaces, managing state, and building navigation.'], links: [{ label: 'Explore SwiftUI learning', href: '/swiftui-training' }, { label: 'About the author', href: '/about' }] },
  ] },
  '/case-studies/vola': { title: 'Vola AI Note Taker — iOS product work | James Thang', description: 'Explore James Thang’s Vola AI Note Taker: live transcription, AI summaries, translation, and questions about recorded notes on iPhone.', eyebrow: 'PRODUCT WALKTHROUGH / iOS', heading: 'Vola — stay in the conversation.', intro: 'Vola is my independent AI note-taking app for iPhone. It brings live transcription, summaries, and questions about notes into a recording experience.', image: require('../../Image/Vola2.png'), imageAlt: 'Vola showing live transcript, AI summary, and Ask AI', appRoute: '/vola', appStore: 'https://apps.apple.com/app/id6758566739', sections: [
    { title: 'From a recording to a useful note', paragraphs: ['Vola lets users see live text while recording, edit notes during the recording, and translate text. AI summaries help turn the captured material into a shorter reference.', 'The Ask AI interface lets users ask questions about their notes. Transcript, summary, and questions are related parts of the same note-taking workflow, rather than separate tasks to assemble manually.'] },
    { title: 'A product lens', paragraphs: ['The key interface challenge in a note-taking tool is helping people find useful information without losing their place in a conversation. Vola’s product experience brings capture and follow-up into one place.', 'For a team planning a similar product, the initial discussion should cover recording behavior, permissions, how transcripts are reviewed, and how generated content is presented to the user. These requirements determine the scope of an implementation.'], links: [{ label: 'Discuss your iOS product', href: '/ios-consulting' }] },
  ] },
  '/case-studies/tidora': { title: 'Tidora Mac Cleaner — macOS product work | James Thang', description: 'Explore James Thang’s Tidora Mac Cleaner, a macOS utility for scanning caches, logs, and unnecessary files to reclaim disk space.', eyebrow: 'PRODUCT WALKTHROUGH / macOS', heading: 'Tidora — make room on your Mac.', intro: 'Tidora is my independent Mac cleaning and maintenance app. It helps users scan caches, logs, and unnecessary files when disk space becomes difficult to manage.', image: require('../../Image/TidyMac1.png'), imageAlt: 'Mac cleaning interface showing application caches and system logs', appRoute: '/tidora', appStore: 'https://apps.apple.com/app/id6747400514', sections: [
    { title: 'Make storage maintenance understandable', paragraphs: ['Storage cleanup begins with understanding what is taking up space. Tidora’s scan interface groups cleaning candidates so the task is easier to review than navigating scattered folders manually.', 'The product focuses on unnecessary files, caches, and logs. Its purpose is to help reclaim disk space through an approachable maintenance workflow.'] },
    { title: 'A product lens', paragraphs: ['For a Mac utility, the interface needs to explain what a scan found and what the proposed action means. File categories, sizes, access permissions, and feedback after an action are useful requirements to define early.', 'If you are planning a desktop utility, bring the file types and workflows you want to support. We can discuss the product scope and how to communicate those operations clearly.'], links: [{ label: 'Discuss a Mac app', href: '/contact' }] },
  ] },
  '/case-studies/horology-studio': { title: 'Horology Studio — iOS watches & widgets | James Thang', description: 'Explore James Thang’s Horology Studio: interactive watches, customization, Home Screen widgets, world time, and system alarms on iOS.', eyebrow: 'PRODUCT WALKTHROUGH / iOS', heading: 'Horology Studio — a timepiece made personal.', intro: 'Horology Studio is my independent interactive watch app for iPhone, combining watch customization with ways to keep time visible beyond the app.', image: require('../../Image/Horology1.png'), imageAlt: 'Horology Studio interactive watch face on iPhone', appRoute: '/horology-studio', appStore: 'https://apps.apple.com/app/id6808155373', sections: [
    { title: 'An experience inside and outside the app', paragraphs: ['Users can customize their timepiece and bring a selected design to a Home Screen widget. World Time widgets offer another way to display watches and cities.', 'On iOS 26 or later, the app supports system-backed alarms with an optional five-minute snooze. The product brings a detailed visual experience together with everyday timekeeping features.'] },
    { title: 'A product lens', paragraphs: ['An interface with widgets and system integrations needs requirements for more than its main screen. Supported OS versions, configuration, and the information shown in each surface are part of the product design.', 'If your iOS app needs a richer experience across app and system surfaces, we can start by identifying what users need in each place.'], links: [{ label: 'Discuss an iOS integration', href: '/ios-consulting' }] },
  ] },
  '/articles': { title: 'iOS & SwiftUI learning notes | James Thang', description: 'Practical iOS learning notes from James Thang, a SwiftUI instructor, technical author, and independent app developer.', eyebrow: 'LEARNING NOTES', heading: 'Make the next decision clearer.', intro: 'Focused explanations for people learning SwiftUI and teams planning iOS interfaces.', sections: [{ title: 'Choosing an interface approach', paragraphs: ['A practical way to discuss SwiftUI, UIKit, and a hybrid interface before deciding on an implementation.'], links: [{ label: 'Read: SwiftUI, UIKit, or both?', href: '/articles/swiftui-or-uikit' }] }, { title: 'Go further', links: [{ label: 'SwiftUI course and learning', href: '/swiftui-training' }, { label: 'Books on SwiftUI and Firebase', href: '/books' }] }] },
  '/articles/swiftui-or-uikit': { title: 'SwiftUI, UIKit, or both? An iOS planning guide | James Thang', description: 'Choose an iOS interface approach by considering your existing code, deployment targets, interactions, and team experience. A guide from James Thang.', eyebrow: 'iOS / INTERFACE PLANNING', heading: 'SwiftUI, UIKit, or both?', intro: 'Start with the product requirements and the code you already have. For an existing app, a focused hybrid approach can be worth evaluating before committing to a broad interface rewrite.', article: true, date: '2026-10-07', sections: [
    { title: 'Ask four questions before choosing', items: ['What is the oldest iOS version the product must support?', 'Which screens already work well, and which need to change?', 'Are there specific controls or interactions the new feature depends on?', 'Which approach can the team implement, review, and maintain confidently?'], paragraphs: ['These questions make a framework discussion concrete. A new settings screen and a complex editor may have different needs, even in the same app. My recommendation is to assess the feature rather than assume one choice must govern every screen.'] },
    { title: 'Use integration as an option', paragraphs: ['Apple supports SwiftUI views inside UIKit through hosting controllers, and UIKit views or view controllers inside SwiftUI through representable wrappers. This allows an existing interface to adopt another approach in a focused area.'], links: [{ label: 'Apple documentation: UIKit integration', href: 'https://developer.apple.com/documentation/swiftui/uikit-integration' }] },
    { title: 'Choose a small feature to evaluate', paragraphs: ['Pick a real screen with a clear acceptance criterion. Review layout, navigation, accessibility, and behavior when content is missing or unusually long. Include the supported device sizes and OS versions in the evaluation.', 'For a hybrid screen, also review where data is owned and how events cross the boundary. A working visual prototype is useful, but it should answer those questions before you treat the approach as settled. This is a planning recommendation, not a benchmark comparing the frameworks.'] },
    { title: 'Treat deployment targets as part of the decision', paragraphs: ['For example, SwiftUI’s support for the Observation framework starts with iOS 17 and macOS 14. A learning example using it needs a compatible deployment target; an app supporting older versions needs a suitable alternative.'], links: [{ label: 'Apple documentation: managing model data', href: 'https://developer.apple.com/documentation/swiftui/managing-model-data-in-your-app' }] },
    { title: 'Make the decision reviewable', paragraphs: ['Write down the chosen approach, the specific feature it applies to, the constraints you checked, and what would make you revisit it. That gives both the developer and the product team a useful reference as the app evolves.'], links: [{ label: 'Discuss an iOS interface', href: '/ios-consulting' }, { label: 'Build your SwiftUI foundations', href: '/swiftui-training' }] },
  ] },
  '/vi/about': { title: 'James Thang — Chuyên gia iOS, tác giả & giảng viên SwiftUI', description: 'Dương Đình Bảo Thăng (James Thang): lập trình viên iOS chuyên SwiftUI và UIKit, tác giả sách SwiftUI và Firebase, giảng viên khóa học SwiftUI.', eyebrow: 'VỀ JAMES', heading: 'Phát triển ứng dụng, viết sách và chia sẻ kiến thức iOS.', intro: 'Tôi là Dương Đình Bảo Thăng, sử dụng tên James Thang trong công việc. Tôi là lập trình viên iOS độc lập chuyên về SwiftUI và UIKit, tác giả sách kỹ thuật và giảng viên khóa học SwiftUI.', translation: '/about', sections: [
    { title: 'Từ giao diện đến phát hành', paragraphs: ['Tôi phát triển ứng dụng cho iPhone và Mac, làm việc với Swift, SwiftUI, UIKit, luồng dữ liệu, tích hợp backend và chuẩn bị phát hành trên App Store.', 'Tôi cũng làm việc với React Native, Codex, Claude Code và Cursor, kết hợp công cụ hỗ trợ với triển khai, rà soát mã nguồn và kiểm thử.'], links: [{ label: 'Trao đổi về dự án iOS (tiếng Anh)', href: '/ios-consulting' }] },
    { title: 'Ứng dụng, sách và khóa học', paragraphs: ['Các sản phẩm độc lập của tôi gồm Vola — ứng dụng ghi chú AI trên iPhone, Tidora — tiện ích dọn dẹp Mac và Horology Studio — trải nghiệm đồng hồ tương tác.', 'Tôi là tác giả Ultimate SwiftUI Handbook for iOS Developers và Ultimate Firebase for iOS and Android Applications, do Orange AVA xuất bản. Khóa học SwiftUI Essentials trên Udemy hướng dẫn xây dựng giao diện, quản lý trạng thái, điều hướng và MVVM.'], links: [{ label: 'Sách đã xuất bản (tiếng Anh)', href: '/books' }, { label: 'Học SwiftUI', href: '/vi/swiftui-training' }] },
    { title: 'Các cách ghi tên trong hồ sơ xuất bản', paragraphs: ['James Thang là tên tôi sử dụng trong công việc; tên tiếng Việt là Dương Đình Bảo Thăng. Nhà xuất bản ghi Dương Đình Bảo (James) Thăng hoặc Duong Dinh Bao (James) Thang. Hồ sơ giảng viên Udemy sử dụng tên Thăng Dương. Các hồ sơ này đều gắn với công việc của tôi.'], links: evidence },
  ] },
  '/vi/swiftui-training': { title: 'Học SwiftUI cùng James Thang | Khóa học & trao đổi', description: 'Khóa học SwiftUI Essentials của James Thang, các chủ đề thực hành, sách SwiftUI và cách trao đổi nhu cầu học tập cá nhân hoặc cho nhóm.', eyebrow: 'DÀNH CHO NGƯỜI HỌC & NHÓM PHÁT TRIỂN', heading: 'Hiểu cách xây dựng giao diện với SwiftUI.', intro: 'Học SwiftUI cùng giảng viên có ứng dụng độc lập và sách về phát triển di động. Bạn có thể bắt đầu với khóa học tự học, sau đó trao đổi những chủ đề cần tìm hiểu sâu hơn.', translation: '/swiftui-training', course: true, sections: [
    { title: 'Bắt đầu với khóa học', paragraphs: ['SwiftUI Essentials: Kickstart Your iOS Development Journey là khóa học bằng tiếng Anh của tôi trên Udemy. Nội dung giới thiệu cách xây dựng giao diện, bố cục, quản lý trạng thái, điều hướng và MVVM.', 'Bạn cần máy Mac có Xcode để thực hành. Kiến thức Swift cơ bản giúp bạn tập trung vào giao diện và luồng dữ liệu. Xem trang Udemy để biết chương trình và thông tin đăng ký hiện tại.'], links: [{ label: 'Xem khóa học và chương trình trên Udemy', href: publisherLinks.course }] },
    { title: 'Những nội dung nên thực hành', items: ['Kết hợp view và các thành phần bố cục để tạo giao diện.', 'Hiểu nơi lưu trạng thái và cách thay đổi dữ liệu cập nhật giao diện.', 'Xây dựng điều hướng giữa các màn hình.', 'Phân chia trách nhiệm của view và model theo MVVM.'], paragraphs: ['Hãy áp dụng từng chủ đề vào một ứng dụng nhỏ của riêng bạn, giải thích lựa chọn và kiểm tra hành vi khi dữ liệu thay đổi.'], links: [{ label: 'Đọc: chọn SwiftUI và UIKit (tiếng Anh)', href: '/articles/swiftui-or-uikit' }] },
    { title: 'Trao đổi nhu cầu học tập', paragraphs: ['Nếu bạn đang tự học hoặc lên kế hoạch học cho nhóm, hãy chia sẻ kinh nghiệm hiện tại, các chủ đề muốn học và ứng dụng muốn xây dựng. Chúng ta có thể trao đổi xem một buổi học tập trung hoặc phạm vi học được điều chỉnh có phù hợp hay không.', 'Bạn cũng có thể tham khảo Ultimate SwiftUI Handbook for iOS Developers để học qua sách.'], links: [{ label: 'Liên hệ về mục tiêu học tập', href: '/contact' }, { label: 'Xem sách (tiếng Anh)', href: '/books' }] },
  ] },
};
